//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryItWebPages.UserAccountService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserAccountService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateAccount", ReplyAction="http://tempuri.org/IService1/CreateAccountResponse")]
        bool CreateAccount(string name, string emailId, string username, string password, string address, string phoneNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateAccount", ReplyAction="http://tempuri.org/IService1/CreateAccountResponse")]
        System.Threading.Tasks.Task<bool> CreateAccountAsync(string name, string emailId, string username, string password, string address, string phoneNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        bool Login(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditAccount", ReplyAction="http://tempuri.org/IService1/EditAccountResponse")]
        bool EditAccount(string name, string emailId, string username, string password, string address, string phoneNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditAccount", ReplyAction="http://tempuri.org/IService1/EditAccountResponse")]
        System.Threading.Tasks.Task<bool> EditAccountAsync(string name, string emailId, string username, string password, string address, string phoneNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TryItWebPages.UserAccountService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TryItWebPages.UserAccountService.IService1>, TryItWebPages.UserAccountService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateAccount(string name, string emailId, string username, string password, string address, string phoneNo) {
            return base.Channel.CreateAccount(name, emailId, username, password, address, phoneNo);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAccountAsync(string name, string emailId, string username, string password, string address, string phoneNo) {
            return base.Channel.CreateAccountAsync(name, emailId, username, password, address, phoneNo);
        }
        
        public bool Login(string username, string password) {
            return base.Channel.Login(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string username, string password) {
            return base.Channel.LoginAsync(username, password);
        }
        
        public bool EditAccount(string name, string emailId, string username, string password, string address, string phoneNo) {
            return base.Channel.EditAccount(name, emailId, username, password, address, phoneNo);
        }
        
        public System.Threading.Tasks.Task<bool> EditAccountAsync(string name, string emailId, string username, string password, string address, string phoneNo) {
            return base.Channel.EditAccountAsync(name, emailId, username, password, address, phoneNo);
        }
    }
}
