//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryItPageForElectiveServices.ValidateCardNumberServie {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValidateCardNumberServie.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/validateCreditCardNumber", ReplyAction="http://tempuri.org/IService1/validateCreditCardNumberResponse")]
        string validateCreditCardNumber(string encryptedCardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/validateCreditCardNumber", ReplyAction="http://tempuri.org/IService1/validateCreditCardNumberResponse")]
        System.Threading.Tasks.Task<string> validateCreditCardNumberAsync(string encryptedCardNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TryItPageForElectiveServices.ValidateCardNumberServie.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TryItPageForElectiveServices.ValidateCardNumberServie.IService1>, TryItPageForElectiveServices.ValidateCardNumberServie.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string validateCreditCardNumber(string encryptedCardNumber) {
            return base.Channel.validateCreditCardNumber(encryptedCardNumber);
        }
        
        public System.Threading.Tasks.Task<string> validateCreditCardNumberAsync(string encryptedCardNumber) {
            return base.Channel.validateCreditCardNumberAsync(encryptedCardNumber);
        }
    }
}
