//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryItPageForElectiveServices.CurrencyConverterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurrencyConverterService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CurrencyConversion", ReplyAction="http://tempuri.org/IService1/CurrencyConversionResponse")]
        string CurrencyConversion(string amount, string toCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CurrencyConversion", ReplyAction="http://tempuri.org/IService1/CurrencyConversionResponse")]
        System.Threading.Tasks.Task<string> CurrencyConversionAsync(string amount, string toCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCurrencyCodes", ReplyAction="http://tempuri.org/IService1/getCurrencyCodesResponse")]
        string getCurrencyCodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getCurrencyCodes", ReplyAction="http://tempuri.org/IService1/getCurrencyCodesResponse")]
        System.Threading.Tasks.Task<string> getCurrencyCodesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/decryption", ReplyAction="http://tempuri.org/IService1/decryptionResponse")]
        string decryption(string cipher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/decryption", ReplyAction="http://tempuri.org/IService1/decryptionResponse")]
        System.Threading.Tasks.Task<string> decryptionAsync(string cipher);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TryItPageForElectiveServices.CurrencyConverterService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TryItPageForElectiveServices.CurrencyConverterService.IService1>, TryItPageForElectiveServices.CurrencyConverterService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CurrencyConversion(string amount, string toCurrency) {
            return base.Channel.CurrencyConversion(amount, toCurrency);
        }
        
        public System.Threading.Tasks.Task<string> CurrencyConversionAsync(string amount, string toCurrency) {
            return base.Channel.CurrencyConversionAsync(amount, toCurrency);
        }
        
        public string getCurrencyCodes() {
            return base.Channel.getCurrencyCodes();
        }
        
        public System.Threading.Tasks.Task<string> getCurrencyCodesAsync() {
            return base.Channel.getCurrencyCodesAsync();
        }
        
        public string decryption(string cipher) {
            return base.Channel.decryption(cipher);
        }
        
        public System.Threading.Tasks.Task<string> decryptionAsync(string cipher) {
            return base.Channel.decryptionAsync(cipher);
        }
    }
}
